### PR TITLE
disallow delete of only SpecRevision

### LINKED ISSUE #257: Registry API: DeleteApiSpecRevision can delete the only remaining revision of a spec
[AIP-162](https://google.aip.dev/162#deleting-revisions) states the following. We don't currently support this expected behavior.

> The method must not cause the resource to be deleted. Because a resource should not exist with zero revisions, the method must fail with FAILED_PRECONDITION if the user attempts to delete the only revision.

We have a [test](https://github.com/apigee/registry/blob/9c0e693d871ddb18e31137a59949bbcebf3fb1f5/server/actions_spec_revisions_test.go#L237) for this case that is currently skipped.

### PR DESCRIPTION
**Pull request by theganyo**
Fixes #257

### CODE REVIEW

File: server/registry/actions_spec_revisions.go [hunk 1]
```diff
@@ -93,6 +93,9 @@ func (s *RegistryServer) DeleteApiSpecRevision(ctx context.Context, req *rpc.Del
 	}
 
 	if err := db.DeleteSpecRevision(ctx, name); err != nil {
+		if _, ok := status.FromError(err); ok {
```
Comment (timburks) [inline server/registry/actions_spec_revisions.go:96]: Could we replace this (and line 99) with a call to grpcErrorFromDBError() ?

Comment (theganyo) [reply server/registry/actions_spec_revisions.go:96]: No, that's a private function to the storage package. But good point: that has already been done by storage, so this doesn't need to translate the error anyway.

**Review by timburks — APPROVED** [review]
