### PR TITLE
ensure SQLite doesn't lose foreign key contraint

### LINKED ISSUE #804: Registry server: DeleteProject cascading deletion fails to delete all child resources
I'm finding that when I delete a project with `--force`, some entries remain in the database.

I can reproduce this using the `samples/googleapis` example in the `registry-experimental` repo:

```
timburks@penguin:~/registry-experimental/samples/googleapis$ registry rpc admin create-project --project_id sample
name:"projects/sample" create_time:{seconds:1667337584 nanos:610439000} update_time:{seconds:1667337584 nanos:610439000}
timburks@penguin:~/registry-experimental/samples/googleapis$ registry apply -f . -R --parent projects/sample/locations/global
  INFO[0000] Applying apis/googleapis.com-apigateway.yaml uid=57d2145d
  INFO[0000] Applying apis/googleapis.com-books.yaml uid=57d2145d
  INFO[0000] Applying apis/googleapis.com-analyticsadmin.yaml uid=57d2145d
  INFO[0000] Applying apis/googleapis.com-apigee.yaml uid=57d2145d
  INFO[0000] Applying apis/googleapis.com-certificatemanager.yaml uid=57d2145d
  INFO[0000] Applying apis/googleapis.com-analyticshub.yaml uid=57d2145d
  INFO[0000] Applying apis/googleapis.com-apigeeregistry.yaml uid=57d2145d
  INFO[0000] Applying apis/googleapis.com-area120tables.yaml uid=57d2145d
  INFO[0000] Applying apis/googleapis.com-assuredworkloads.yaml uid=57d2145d
  INFO[0000] Applying apis/googleapis.com-beyondcorp.yaml uid=57d2145d
  INFO[0001] Applying apis/googleapis.com-clouddeploy.yaml uid=57d2145d
  INFO[0002] Applying apis/googleapis.com-clouderrorreporting.yaml uid=57d2145d
  INFO[0005] Applying apis/googleapis.com-cloudfunctions.yaml uid=57d2145d
  INFO[0005] Applying apis/googleapis.com-containeranalysis.yaml uid=57d2145d
  INFO[0005] Applying apis/googleapis.com-datapipelines.yaml uid=57d2145d
  INFO[0005] Applying apis/googleapis.com-datastream.yaml uid=57d2145d
  INFO[0006] Applying apis/googleapis.com-essentialcontacts.yaml uid=57d2145d
  INFO[0006] Applying apis/googleapis.com-factchecktools.yaml uid=57d2145d
  INFO[0006] Applying apis/googleapis.com-firebase.yaml uid=57d2145d
  INFO[0006] Applying apis/googleapis.com-gkehub.yaml uid=57d2145d
  INFO[0006] Applying apis/googleapis.com-mybusinessqanda.yaml uid=57d2145d
  INFO[0006] Applying apis/googleapis.com-networkservices.yaml uid=57d2145d
  INFO[0007] Applying apis/googleapis.com-oauth2.yaml uid=57d2145d
  INFO[0007] Applying apis/googleapis.com-paymentsresellersubscription.yaml uid=57d2145d
  INFO[0007] Applying apis/googleapis.com-playdeveloperreporting.yaml uid=57d2145d
  INFO[0007] Applying apis/googleapis.com-policyanalyzer.yaml uid=57d2145d
  INFO[0008] Applying apis/googleapis.com-policytroubleshooter.yaml uid=57d2145d
  INFO[0009] Applying apis/googleapis.com-prod-tt-sasportal.yaml uid=57d2145d
  INFO[0009] Applying apis/googleapis.com-proximitybeacon.yaml uid=57d2145d
  INFO[0009] Applying apis/googleapis.com-pubsub.yaml uid=57d2145d
  INFO[0009] Applying apis/googleapis.com-pubsublite.yaml uid=57d2145d
  INFO[0011] Applying apis/googleapis.com-recaptchaenterprise.yaml uid=57d2145d
  INFO[0012] Applying apis/googleapis.com-translate.yaml uid=57d2145d
  INFO[0012] Applying apis/googleapis.com-vision.yaml uid=57d2145d
  INFO[0013] Applying apis/googleapis.com-youtube.yaml uid=57d2145d
  INFO[0021] Applying artifacts/apihub-display-settings.yaml uid=57d2145d
  INFO[0021] Applying artifacts/apihub-styleguide.yaml uid=57d2145d
  INFO[0021] Applying artifacts/apihub-taxonomies.yaml uid=57d2145d
  INFO[0021] Applying artifacts/apihub-lifecycle.yaml uid=57d2145d
  INFO[0021] Applying artifacts/apihub-lint-error-percentage.yaml uid=57d2145d
  INFO[0021] Applying artifacts/apihub-lint-summary.yaml uid=57d2145d
  INFO[0021] Applying artifacts/apihub-manifest.yaml uid=57d2145d
  INFO[0021] Applying artifacts/apihub-lint-warnings.yaml uid=57d2145d
  INFO[0021] Applying artifacts/apihub-lint-errors.yaml uid=57d2145d
  INFO[0021] Applying artifacts/apihub-lint-errors-exist.yaml uid=57d2145d
  INFO[0021] Applying lifecycle.yaml   uid=57d2145d
timburks@penguin:~/registry-experimental/samples/googleapis$ registry rpc admin get-storage --json
{
  "description": "sqlite",
  "collections": [
    {
      "name": "apis",
      "count": "35"
    },
    {
      "name": "artifacts",
      "count": "10"
    },
    {
      "name": "blobs",
      "count": "69"
    },
    {
      "name": "deployment_revision_tags"
    },
    {
      "name": "deployments"
    },
    {
      "name": "projects",
      "count": "1"
    },
    {
      "name": "spec_revision_tags"
    },
    {
      "name": "specs",
      "count": "59"
    },
    {
      "name": "versions",
      "count": "59"
    }
  ]
}
timburks@penguin:~/registry-experimental/samples/googleapis$ registry rpc admin delete-project --name projects/sample --force
timburks@penguin:~/registry-experimental/samples/googleapis$ registry rpc admin get-storage --json
{
  "description": "sqlite",
  "collections": [
    {
      "name": "apis",
      "count": "35"
    },
    {
      "name": "artifacts"
    },
    {
      "name": "blobs"
    },
    {
      "name": "deployment_revision_tags"
    },
    {
      "name": "deployments"
    },
    {
      "name": "projects"
    },
    {
      "name": "spec_revision_tags"
    },
    {
      "name": "specs",
      "count": "59"
    },
    {
      "name": "versions",
      "count": "59"
    }
  ]
}
```

Note that although projects, artifacts, and blobs are all deleted in the above example, apis, versions, and specs are not.

So far I've only observed this in SQLite.

### PR DESCRIPTION
**Pull request by theganyo**
Fixes #804

### CODE REVIEW

File: server/registry/internal/storage/client.go [hunk 1]
```diff
@@ -65,13 +64,18 @@ func NewClient(ctx context.Context, driver, dsn string) (*Client, error) {
 			c.close()
 			return nil, grpcErrorForDBError(ctx, err)
 		}
-		// eliminate multithreading contention
+		// Sets to 1 to disabllow multiple connections on SQLite.
```
Comment (timburks) [inline server/registry/internal/storage/client.go:67]: nit: "disallow"

**Review by timburks — APPROVED** [review]
🎉
